### ISSUE TITLE
`require': cannot load such file -- curses (LoadError)

### ISSUE THREAD

**Issue by dechimp** [scudco/minesweeprb#1]
Unable to find the curses gem for some reason. `gem install curses` seems to fix the issue.
```
❯ minesweeprb
Traceback (most recent call last):
        13: from /Users/dechimp/.rbenv/versions/2.6.5/bin/minesweeprb:23:in `<main>'
        12: from /Users/dechimp/.rbenv/versions/2.6.5/bin/minesweeprb:23:in `load'
        11: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minesweeprb-0.3.0/exe/minesweeprb:14:in `<top (required)>'
        10: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         9: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         8: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         6: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minesweeprb-0.3.0/lib/minesweeprb/cli.rb:30:in `play'
         5: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minesweeprb-0.3.0/lib/minesweeprb/cli.rb:30:in `require_relative'
         4: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minesweeprb-0.3.0/lib/minesweeprb/commands/play.rb:7:in `<top (required)>'
         3: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minesweeprb-0.3.0/lib/minesweeprb/commands/play.rb:7:in `require_relative'
         2: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minesweeprb-0.3.0/lib/minesweeprb/gameboard.rb:3:in `<top (required)>'
         1: from /Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/dechimp/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- curses (LoadError)
 ```

**Comment by sdhull** [comment]
I believe it just needs to be added to the `gemspec`
If you just do `gem install curses` in the meantime it should work. Can you confirm @dechimp?

**Comment by sdhull** [comment]
Looks like this has been resolved in the latest version @scudco you should close this
